[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.2"
bevy_renet = "3.0.0"
game_core = { path = "../game_core" }
bevy-inspector-egui = "0.35.0"
bevy_egui = "0.38.0"
