[package]
name = "game_core"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.2"
bevy_renet = "3.0.0"
bincode = { version = "2.0.1", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
